library(devtools)
library(BiocCheck)
document("~/workspace/fastGenoGAM")
test("~/workspace/fastGenoGAM")
check("~/workspace/fastGenoGAM")
BiocCheck("~/workspace/fastGenoGAM")
install("~/workspace/fastGenoGAM")
