// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// multiply_
arma::sp_mat multiply_(arma::sp_mat X, arma::sp_mat Y);
RcppExport SEXP _fastGenoGAM_multiply_(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// compute_hessian_
arma::sp_mat compute_hessian_(arma::sp_mat X, arma::sp_mat Y);
RcppExport SEXP _fastGenoGAM_compute_hessian_(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hessian_(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// trans_
arma::sp_mat trans_(arma::sp_mat X);
RcppExport SEXP _fastGenoGAM_trans_(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(trans_(X));
    return rcpp_result_gen;
END_RCPP
}
// vecmult_
arma::mat vecmult_(arma::sp_mat X, arma::mat Y);
RcppExport SEXP _fastGenoGAM_vecmult_(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(vecmult_(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// ll_pen_nb
double ll_pen_nb(arma::vec beta, arma::sp_mat X, arma::vec y, arma::vec offset, double theta, double lambda, arma::sp_mat S, double ll_factor, double lambda_factor, int n);
RcppExport SEXP _fastGenoGAM_ll_pen_nb(SEXP betaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP lambdaSEXP, SEXP SSEXP, SEXP ll_factorSEXP, SEXP lambda_factorSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type ll_factor(ll_factorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(ll_pen_nb(beta, X, y, offset, theta, lambda, S, ll_factor, lambda_factor, n));
    return rcpp_result_gen;
END_RCPP
}
// gr_ll_pen_nb
arma::vec gr_ll_pen_nb(arma::vec beta, arma::sp_mat X, arma::vec y, arma::vec offset, double theta, double lambda, arma::sp_mat S);
RcppExport SEXP _fastGenoGAM_gr_ll_pen_nb(SEXP betaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP lambdaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(gr_ll_pen_nb(beta, X, y, offset, theta, lambda, S));
    return rcpp_result_gen;
END_RCPP
}
// gr_ll_pen_nb_alt
arma::vec gr_ll_pen_nb_alt(arma::vec beta, arma::sp_mat X, arma::sp_mat XT, arma::vec y, arma::vec offset, double theta, double lambda, arma::sp_mat S);
RcppExport SEXP _fastGenoGAM_gr_ll_pen_nb_alt(SEXP betaSEXP, SEXP XSEXP, SEXP XTSEXP, SEXP ySEXP, SEXP offsetSEXP, SEXP thetaSEXP, SEXP lambdaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type XT(XTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(gr_ll_pen_nb_alt(beta, X, XT, y, offset, theta, lambda, S));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastGenoGAM_multiply_", (DL_FUNC) &_fastGenoGAM_multiply_, 2},
    {"_fastGenoGAM_compute_hessian_", (DL_FUNC) &_fastGenoGAM_compute_hessian_, 2},
    {"_fastGenoGAM_trans_", (DL_FUNC) &_fastGenoGAM_trans_, 1},
    {"_fastGenoGAM_vecmult_", (DL_FUNC) &_fastGenoGAM_vecmult_, 2},
    {"_fastGenoGAM_ll_pen_nb", (DL_FUNC) &_fastGenoGAM_ll_pen_nb, 10},
    {"_fastGenoGAM_gr_ll_pen_nb", (DL_FUNC) &_fastGenoGAM_gr_ll_pen_nb, 7},
    {"_fastGenoGAM_gr_ll_pen_nb_alt", (DL_FUNC) &_fastGenoGAM_gr_ll_pen_nb_alt, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastGenoGAM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
