# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ll_pen_nb <- function(beta, X, y, offset, theta, lambda, S, ll_factor, lambda_factor, n) {
    .Call('_fastGenoGAM_ll_pen_nb', PACKAGE = 'fastGenoGAM', beta, X, y, offset, theta, lambda, S, ll_factor, lambda_factor, n)
}

gr_ll_pen_nb <- function(beta, X, XT, y, offset, theta, lambda, S) {
    .Call('_fastGenoGAM_gr_ll_pen_nb', PACKAGE = 'fastGenoGAM', beta, X, XT, y, offset, theta, lambda, S)
}

compute_pen_hessian <- function(beta, X, XT, offset, y, S, lambda, theta) {
    .Call('_fastGenoGAM_compute_pen_hessian', PACKAGE = 'fastGenoGAM', beta, X, XT, offset, y, S, lambda, theta)
}

compute_stdError <- function(X, H) {
    .Call('_fastGenoGAM_compute_stdError', PACKAGE = 'fastGenoGAM', X, H)
}

inverseH <- function(L, r, c, x) {
    .Call('_fastGenoGAM_inverseH', PACKAGE = 'fastGenoGAM', L, r, c, x)
}

