# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiply_ <- function(X, Y) {
    .Call('_fastGenoGAM_multiply_', PACKAGE = 'fastGenoGAM', X, Y)
}

compute_hessian_ <- function(X, Y) {
    .Call('_fastGenoGAM_compute_hessian_', PACKAGE = 'fastGenoGAM', X, Y)
}

trans_ <- function(X) {
    .Call('_fastGenoGAM_trans_', PACKAGE = 'fastGenoGAM', X)
}

vecmult_ <- function(X, Y) {
    .Call('_fastGenoGAM_vecmult_', PACKAGE = 'fastGenoGAM', X, Y)
}

ll_pen_nb <- function(beta, X, y, offset, theta, lambda, S, ll_factor, lambda_factor, n) {
    .Call('_fastGenoGAM_ll_pen_nb', PACKAGE = 'fastGenoGAM', beta, X, y, offset, theta, lambda, S, ll_factor, lambda_factor, n)
}

gr_ll_pen_nb <- function(beta, X, y, offset, theta, lambda, S) {
    .Call('_fastGenoGAM_gr_ll_pen_nb', PACKAGE = 'fastGenoGAM', beta, X, y, offset, theta, lambda, S)
}

gr_ll_pen_nb_alt <- function(beta, X, XT, y, offset, theta, lambda, S) {
    .Call('_fastGenoGAM_gr_ll_pen_nb_alt', PACKAGE = 'fastGenoGAM', beta, X, XT, y, offset, theta, lambda, S)
}

